SET default_tablespace = '';
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES ( 1, 1, 1,'MSG','ALPHABET MESAGE TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES ( 2, 1, 1,'HDR','ALPHABET HEADER TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES ( 3, 1, 1,'FTR','ALPHABET FOOTER TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES ( 4, 1, 1,'FRM','ALPHABET   FROM TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES ( 5, 1, 1, 'TO','ALPHABET     TO TEXT');

INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES ( 6, 1, 2,'MSG','GOOGLE MESAGE TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES ( 7, 1, 2,'HDR','GOOGLE HEADER TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES ( 8, 1, 2,'FTR','GOOGLE FOOTER TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES ( 9, 1, 2,'FRM','GOOGLE   FROM TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (10, 1, 2, 'TO','GOOGLE     TO TEXT');

INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (11, 1, 3,'MSG','WAYMO MESAGE TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (12, 1, 3,'HDR','WAYMO HEADER TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (13, 1, 3,'FTR','WAYMO FOOTER TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (14, 1, 3,'FRM','WAYMO   FROM TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (15, 1, 3, 'TO','WAYMO     TO TEXT');

INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (16, 2, 1,'MSG','APPLE MESAGE TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (17, 2, 1,'HDR','APPLE HEADER TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (18, 2, 1,'FTR','APPLE FOOTER TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (19, 2, 1,'FRM','APPLE   FROM TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (20, 2, 1, 'TO','APPLE     TO TEXT');

INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (21, 3, 1,'MSG','AMAZON MESAGE TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (22, 3, 1,'HDR','AMAZON HEADER TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (23, 3, 1,'FTR','AMAZON FOOTER TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (24, 3, 1,'FRM','AMAZON   FROM TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (25, 3, 1, 'TO','AMAZON     TO TEXT');

INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (26, 4, 1,'MSG','ACME MESAGE TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (27, 4, 1,'HDR','ACME HEADER TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (28, 4, 1,'FTR','ACME FOOTER TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (29, 4, 1,'FRM','ACME   FROM TEXT');
INSERT INTO KEY_VALUE (ID, CATEGORY_ID,SUB_CATEGORY_ID,KEY,VALUE) VALUES (30, 4, 1, 'TO','ACME     TO TEXT');

ALTER TABLE ONLY public.key_value
    ADD CONSTRAINT KEY_VALUE_pkey PRIMARY KEY (id);

--GRANT ALL ON SCHEMA public TO postgres;
--GRANT ALL ON SCHEMA public TO public;